actors:
  4n3i:
    image_url: /images/actors/alice.png
    name: 4n3i
    url: https://twitter.com/4n3i_
author: 4n3i
description: in progress
description_long: 日々の進捗を話すやつ
email:
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: riri-suno-to
itunes_podcast_url:
keywords: comma,separated,keywords
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: riri-suno-to.radio
url:
