actors:
  hoge:
    image_url: /images/actors/alice.png
    name: hoge
    url: http://sns.example.com/alice
  fuga:
    image_url: /images/actors/bob.png
    name: fuga
    url: http://sns.example.com/bob
author: hoge
description: Example description
description_long: Example long description
email: info@example.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: examplehashtag
itunes_podcast_url:
keywords: comma,separated,keywords
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: Example title
url: http://example.com
